export enum Phase {
  SETUP = "SETUP",
  INTRO = "INTRO",
  ROUND_INTRO = "ROUND_INTRO",
  EATING = "EATING",
  MINIGAME_INTRO = "MINIGAME_INTRO",
  MINIGAME_PLAY = "MINIGAME_PLAY",
  TURN_RESULTS = "TURN_RESULTS",
  ROUND_RESULTS = "ROUND_RESULTS",
  FINAL_RESULTS = "FINAL_RESULTS"
}
