import { hostCopy } from "../../copy/host";

export const hostPlaceholderCopy = {
  title: hostCopy.placeholderTitle,
  description: hostCopy.placeholderDescription,
  nextPhaseButtonLabel: hostCopy.nextPhaseButtonLabel,
  teamSetupTitle: hostCopy.teamSetupTitle,
  teamSetupDescription: hostCopy.teamSetupDescription,
  teamNameInputLabel: hostCopy.teamNameInputLabel,
  teamNameInputPlaceholder: hostCopy.teamNameInputPlaceholder,
  createTeamButtonLabel: hostCopy.createTeamButtonLabel,
  playersSectionTitle: hostCopy.playersSectionTitle,
  teamsSectionTitle: hostCopy.teamsSectionTitle,
  eatingParticipationDescription: hostCopy.eatingParticipationDescription,
  loadingStateLabel: hostCopy.loadingStateLabel,
  setupLockedLabel: hostCopy.setupLockedLabel,
  unassignedOptionLabel: hostCopy.unassignedOptionLabel,
  assignmentSelectLabel: hostCopy.assignmentSelectLabel,
  noPlayersLabel: hostCopy.noPlayersLabel,
  noTeamsLabel: hostCopy.noTeamsLabel,
  noAssignedTeamLabel: hostCopy.noAssignedTeamLabel,
  assignedTeamLabel: hostCopy.assignedTeamLabel,
  ateWingLabel: hostCopy.ateWingLabel,
  wingParticipationToggleLabel: hostCopy.wingParticipationToggleLabel,
  triviaSectionDescription: hostCopy.triviaSectionDescription,
  triviaLockedDescription: hostCopy.triviaLockedDescription,
  triviaUnlockedDescription: hostCopy.triviaUnlockedDescription,
  triviaActiveTeamLabel: hostCopy.triviaActiveTeamLabel,
  passAndPlayLockedStateLabel: hostCopy.passAndPlayLockedStateLabel,
  passAndPlayUnlockedStateLabel: hostCopy.passAndPlayUnlockedStateLabel,
  passAndPlayHoldToUnlockButtonLabel: hostCopy.passAndPlayHoldToUnlockButtonLabel,
  passAndPlayHoldInProgressLabel: hostCopy.passAndPlayHoldInProgressLabel,
  passAndPlayRelockButtonLabel: hostCopy.passAndPlayRelockButtonLabel,
  triviaQuestionLabel: hostCopy.triviaQuestionLabel,
  triviaAnswerLabel: hostCopy.triviaAnswerLabel,
  triviaCorrectButtonLabel: hostCopy.triviaCorrectButtonLabel,
  triviaIncorrectButtonLabel: hostCopy.triviaIncorrectButtonLabel,
  teamMembersLabel: hostCopy.teamMembersLabel
} as const;
