export const anamorphLabCopy = {
  title: "ANAMORPH Feel Lab",
  description:
    "Throwaway lab for WN-16. Drive the four knobs, record the numbers, then delete this route in WN-14.",
  cloudLabel: "TV",
  previewLabel: "Tablet preview",
  controlsLabel: "Controls",
  jitterLabel: "1 · Jitter magnitude",
  jitterHint: "Ray-offset scale. 0 is a flat cutout (legible everywhere); high never resolves.",
  curveLabel: "2 · Legibility curve",
  curveHint: "Linear is the untouched geometry. Snap holds it scrambled, then collapses late.",
  curveLinearLabel: "Linear ramp",
  curveSnapLabel: "Late hard snap",
  mirrorLabel: "3 · Antipodal mirror",
  mirrorHint:
    "Parallel jitter makes the opposite angle resolve mirrored. Eye-ray jitter breaks it.",
  mirrorOnLabel: "Resolves (parallel)",
  mirrorOffLabel: "Broken (eye ray)",
  idiomLabel: "4 · Control idiom",
  idiomHint: "Two dials are precise on a greasy tablet; orbit-drag is more natural but slippery.",
  idiomDialsLabel: "Two dials",
  idiomOrbitLabel: "Drag to orbit",
  previewToggleLabel: "4b · Tablet preview",
  previewHint: "Does the dialer need their own small cloud, or does the TV hold up across a room?",
  previewOnLabel: "TV + preview",
  previewOffLabel: "TV only",
  silhouetteLabel: "Silhouette",
  seedLabel: "Seed",
  rerollLabel: "Reroll",
  yawLabel: "Yaw",
  pitchLabel: "Pitch",
  telemetryLabel: "Telemetry",
  telemetryHint: "Off while judging feel; on to record the numbers.",
  showLabel: "Show",
  hideLabel: "Hide",
  angularErrorLabel: "Angular error",
  trueAngleLabel: "True angle",
  snapToTrueLabel: "Snap to true angle",
  snapToMirrorLabel: "Snap to antipode",
  orbitHint: "Drag the cloud to orbit."
} as const;
